### PR TITLE
Updated plugin for HG >= v1.1

### PR DESCRIPTION
**Pull request by genemars**
Hi @swaner ,

here is the updated plugin to work with latest HG. Also auto-reformatted code.

Cheers,
g.

### CODE REVIEW

**Comment by swaner** [comment]
Hi @genielabs 

Great that you thought of this, thank you! Still didn't work when I tried thought but I can do some debugging of why later.

/ Johan

**Comment by swaner** [comment]
I am having issues with row 66 on _systemsettings.js. When I change this:
  response = eval(response.textContent || response.innerText)[0];
 to this
 response = JSON.parse(response.textContent || response.innerText); I got it to work.
But the AddonInstall still fails

/ Johan

**Comment by swaner** [comment]
I think I found the other issue when installing. I made a pull request to show you what I made: https://github.com/genielabs/HomeGenie/pull/231. Two small fixes.

Cheers!

**Comment by genemars** [comment]
thanks for pointing to this. also add-on downloading was not working see:

https://github.com/genielabs/HomeGenie/commit/bc84b28d59dc1e948af995f4a11888940e731c96

**Pull request merged**
